# name: Challenge01
# on: [push]
# jobs:
#   job_1:
#     runs-on: ubuntu-latest
#     steps:
#       - name: print date
#         run: date +%Y-%m-%d
#   job_2:
#     runs-on: windows-latest
#     steps:
#       - name: print date
#         run: (Get-Date).ToString("yyyy-MM-dd")
#   job_3:
#     runs-on: macos-latest
#     steps:
#       - name: print date
#         shell: bash
#         run: date +%Y-%m-%d
#   job_4:
#     runs-on: ubuntu-latest
#     needs: [job_1, job_2, job_3]
#     steps:
#       - name: print date
#         shell: bash
#         run: date +%Y-%m-%d
