name: Demo

on: [push]

env:
  PACKAGE_NAME: demopack

jobs:
  testing:
    name: testing-job
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: greet-people
        run: |
          echo Hello People
          echo Hello People
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python --version
          pip install -r requirements.txt
          pytest --version
      - name: run test
        env:
          REPORT_OUTPUT: reports.md
        run: |
          pytest --junit-xml=reports.xml
      - name: Surface failing tests
        if: always()
        uses: pmeier/pytest-results-action@main
        with:
          # A list of JUnit XML files, directories containing the former, and wildcard
          # patterns to process.
          # See @actions/glob for supported patterns.
          path: reports.xml

          # (Optional) Add a summary of the results at the top of the report
          summary: true

          # (Optional) Select which results should be included in the report.
          # Follows the same syntax as `pytest -r`
          display-options: fEX

          # (Optional) Fail the workflow if no JUnit XML was found.
          fail-on-empty: true

          # (Optional) Title of the test results section in the workflow summary
          title: Test results

  build:
    needs: [testing]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Build package
        run: |
          python -m pdm build
      - name: uploading package
        uses: actions/upload-artifact@v3
        with:
          name: ${{env.PACKAGE_NAME}}
          path: dist/
