name: Demo

on: [push]

jobs:
  testing:
    name: testing-job
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: greet-people
        run: echo Hello People
      - name: greet-multiline
        run: |
          echo "First line",
          echo "Second line."
      - name: run test
        run: pytest --junit-xml=path ./reports.xml
  build:
    needs: [testing]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: run test
        run: pytest --junit-xml=path ./reports.xml